#!/bin/bash

function is_x1_carbon() {
  grep "ThinkPad X1 Carbon" /sys/class/dmi/id/product_family &> /dev/null
  return $?
}

function enable_touch_gestures()
{
  if xinput --list $1 &> /dev/null
  then
    xinput set-prop $1 "libinput Tapping Enabled" 1
    xinput set-prop $1 "libinput Natural Scrolling Enabled" 1
  fi
}

# Enable touch gestures for X1 Carbon
enable_touch_gestures "Synaptics TM3289-021"
